### ISSUE TITLE
Um erro do tipo E_ERROR foi causado na linha 20

### ISSUE THREAD

**Issue by jhonisbs** [DevelopersRede/woocommerce#21]
Instala, ativa, mas quando vou acessar as configurações dentro do woocommerce ele gera o erro abaixo:

Um erro do tipo E_ERROR foi causado na linha 20 do arquivo /home/63789-82454.cloudwaysapps.com/ptwuwnxwuz/public_html/wp-content/plugins/rede-woocommerce/includes/class-wc-rede-api.php. Mensagem de erro: Uncaught Error: Class ‘Rede\Environment’ not found in /home/63789-82454.cloudwaysapps.com/ptwuwnxwuz/public_html/wp-content/plugins/rede-woocommerce/includes/class-wc-rede-api.php:20 Stack trace: #0 /home/63789-82454.cloudwaysapps.com/ptwuwnxwuz/public_html/wp-content/plugins/rede-woocommerce/includes/class-wc-rede-credit.php(45): WC_Rede_API->__construct(Object(WC_Rede_Credit)) #1 /home/63789-82454.cloudwaysapps.com/ptwuwnxwuz/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(94): WC_Rede_Credit->__construct() #2 /home/63789-82454.cloudwaysapps.com/ptwuwnxwuz/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init() #3 /home/63789-82454.cloudwaysapps.com/ptwuwnxwuz/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__construct() #4 /home/63789-82454.cloudwaysapps.com/ptwuwnxwuz/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(817): WC_Payme

**Comment by netojoaobatista** [comment]
https://github.com/DevelopersRede/woocommerce#instala%C3%A7%C3%A3o
