### ISSUE TITLE
Erro: Internal Server Error

### ISSUE THREAD

**Issue by denisoncarlos** [DevelopersRede/woocommerce#6]
Estou com o seguinte problema:

O cliente acessa, adiciona os produtos no Carrinho e na hora de efetivar o pagamento, o sistema começa a processar e retorna a mensagem **Internal Server Error**. O cliente, por não ter nenhuma mensagem de confirmação do pagamento, clica outra vez no botão para pagar e às vezes isso se repete até 6x. O Pedido do cliente entra na loja as 6x e em alguns casos (conforme o limite do cartão) TODOS eles são aprovados, ou seja, aparecem no Painel da Loja com o status Processando.

Isso têm gerado transtorno a um cliente meu, pois além de precisar reembolsar os pedidos "duplicados", a taxa de conversão dele caiu por muitos julgarem como fraude.

O plugin foi instalado devidamente como manda o Readme. Inclusive, tudo está atualizado, tanto o PHP (7.1 com as configurações exigidas pelo WooCommerce), como o WordPress (5.2) e o WooCommerce (3.6.3).

Como posso resolver isso?

**Comment by netojoaobatista** [comment]
Foi feita a instalação com composer, conforme [ilustrado no README.md](https://github.com/DevelopersRede/woocommerce#instala%C3%A7%C3%A3o)?

**Comment by denisoncarlos** [comment]
> Foi feita a instalação com composer, conforme [ilustrado no README.md](https://github.com/DevelopersRede/woocommerce#instala%C3%A7%C3%A3o)?

@netojoaobatista, a princípio havia sido instalado sim. Mas mudamos de servidor e solicitei ao Suporte da hospedagem para realizar a verificação, pois pelo acesso SSH aparece um erro. Estou aguardando e assim que respondido o meu Ticket, retorno a você.

**Comment by netojoaobatista** [comment]
@denisoncarlos, eu fiz uma atualização agora - a versão 1.1. O [rede-woocommerce.zip](https://github.com/DevelopersRede/woocommerce/releases/download/1.1.2/rede-woocommerce.zip) já está pronto; basta fazer upload para o servidor.

**Comment by mvjoias** [comment]
Alguém poderia me ajudar a configurar o sistema no WordPress? A instalação foi feita conforme o readme.md e a versão do PHP é a 5.6. Agradeço!

**Comment by denisoncarlos** [comment]
> @denisoncarlos, eu fiz uma atualização agora - a versão 1.1.2. O [rede-woocommerce.zip](https://github.com/DevelopersRede/woocommerce/releases/download/1.1.2/rede-woocommerce.zip) já está pronto; basta fazer upload para o servidor.

@netojoaobatista, está funcionando perfeitamente! Creio que só precise de uns ajustes na tradução de alguns campos. Se precisar, me dá um toque! Me passando o arquivo base de idioma (.pot), consigo te disponibilizar os arquivos .po e .mo.

**Comment by netojoaobatista** [comment]
@denisoncarlos, nesse instante são utilizados strings literais e todos os arquivos estão aqui nesse repositório. Caso queira internacionalizar, será um prazer aceitar seu PR.

:D
